export const cardData = [
  {
    id: 'knd3003',
    path: 'knd/3003.png',
    title: '音楽が見せてくれる世界 ',
    subtitle: '宵崎奏 - スクランブル・ファンフェスタ！（3星) ',
    prelink: 'https://www.bilibili.com/video/BV1nT4y1Z7S3',
    postlink: 'https://www.bilibili.com/video/BV1nT4y1Z7S3',
  },
  {
    id: 'mfy4005',
    path: 'mfy/4005.png',
    title: 'あたたかい愛情の記憶 ',
    subtitle: '朝比奈真冬 - 灯のミラージュ（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1nT4y1Z7S3',
    postlink: 'https://www.bilibili.com/video/BV1nT4y1Z7S3',
  },
  {
    id: 'mzk4004',
    path: 'mzk/4004.png',
    title: 'ひとときの安息 ',
    subtitle: '晓山瑞希 - 灯のミラージュ（4星) ',
    prelink: 'https://www.bilibili.com/video/BV14h411n7qp',
    postlink: 'https://www.bilibili.com/video/BV14h411n7qp',
  },
  {
    id: 'rin4001',
    path: 'rin/4001.png',
    title: '取り消したメッセージ ',
    subtitle: '镜音铃 - 灯のミラージュ（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1Kb4y117do',
    postlink: 'https://www.bilibili.com/video/BV1Kb4y117do',
  },
  {
    id: 'ena3002',
    path: 'ena/3002.png',
    title: 'アルバムのあの子 ',
    subtitle: '东云绘名 - 灯のミラージュ（3星) ',
    prelink: 'https://www.bilibili.com/video/BV1vb4y1y7Yk',
    postlink: 'https://www.bilibili.com/video/BV1vb4y1y7Yk',
  },
  {
    id: 'knd2003',
    path: 'knd/2003.png',
    title: '不器用なティータイム ',
    subtitle: '宵崎奏 - 灯のミラージュ（2星) ',
    prelink: 'https://www.bilibili.com/video/BV16v411n7nu',
    postlink: 'https://www.bilibili.com/video/BV16v411n7nu',
  },
  {
    id: 'mfy2003',
    path: 'mfy/2003.png',
    title: '見上げる月は同じ ',
    subtitle: '朝比奈真冬 - ふたり、月うさぎ（2星) ',
    prelink: 'https://www.bilibili.com/video/BV1nf4y1N7Kg',
    postlink: 'https://www.bilibili.com/video/BV1nf4y1N7Kg',
  },
  {
    id: 'ena4005',
    path: 'ena/4005.png',
    title: 'いつかの夏祭り ',
    subtitle: '东云绘名 - 夏祭り、鳴り響く音は（4星) ',
    prelink: 'https://www.bilibili.com/video/BV16v411n7nu',
    postlink: 'https://www.bilibili.com/video/BV16v411n7nu',
  },
  {
    id: 'mzk2003',
    path: 'mzk/2003.png',
    title: 'サマーナイトフェスティバル',
    subtitle: '晓山瑞希 - 夏祭り、鳴り響く音は（2星) ',
    prelink: 'https://www.bilibili.com/video/BV1J64y167ii',
    postlink: 'https://www.bilibili.com/video/BV1J64y167ii',
  },
  {
    id: 'knd4004',
    path: 'knd/4004.png',
    title: '思い出の花壇',
    subtitle: '宵崎奏 - カーネーション・リコレクション（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1Xf4y1t77Q',
    postlink: 'https://www.bilibili.com/video/BV1Xf4y1t77Q',
  },
  {
    id: 'mfy4004',
    path: 'mfy/4004.png',
    title: 'こぼれたほほ笑み',
    subtitle: '朝比奈真冬 - カーネーション・リコレクション（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1cy4y1M7Uj',
    postlink: 'https://www.bilibili.com/video/BV1cy4y1M7Uj',
  },
  {
    id: 'luka4001',
    path: 'luka/4001.png',
    title: '私は私のやりかたで',
    subtitle: '巡音流歌 - カーネーション・リコレクション（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1NL411s7wm',
    postlink: 'https://www.bilibili.com/video/BV1NL411s7wm',
  },
  {
    id: 'mzk3003',
    path: 'mzk/3003.png',
    title: '迷える手を引いて',
    subtitle: '晓山瑞希 - カーネーション・リコレクション（3星) ',
    prelink: 'https://www.bilibili.com/video/BV1764y197Cn',
    postlink: 'https://www.bilibili.com/video/BV1764y197Cn',
  },
  {
    id: 'ena2003',
    path: 'ena/2003.png',
    title: '言葉にしてほしくて',
    subtitle: '东云绘名 - カーネーション・リコレクション（2星) ',
    prelink: 'https://www.bilibili.com/video/BV13V411x7n8',
    postlink: 'https://www.bilibili.com/video/BV13V411x7n8',
  },
  {
    id: 'mzk4003',
    path: 'mzk/4003.png',
    title: '想いと現実の狭間で',
    subtitle: '晓山瑞希 - お悩み聞かせて！わくわくピクニック（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1V54y1L7GB',
    postlink: 'https://www.bilibili.com/video/BV1V54y1L7GB',
  },
  {
    id: 'ena4004',
    path: 'ena/4004.png',
    title: '差しのべられた手',
    subtitle: '东云绘名 - お悩み聞かせて！わくわくピクニック（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1HA411G7hL',
    postlink: 'https://www.bilibili.com/video/BV1HA411G7hL',
  },
  {
    id: 'mzk4002',
    path: 'mzk/4002.png',
    title: '気づいてしまった想い',
    subtitle: '晓山瑞希 - シークレット・ディスタンス（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1b5411c7LU',
    postlink: 'https://www.bilibili.com/video/BV1b5411c7LU',
  },
  {
    id: 'ena4003',
    path: 'ena/4003.png',
    title: 'ミステリーツアーの洗礼？',
    subtitle: '东云绘名 - シークレット・ディスタンス（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1xK4y1K7js',
    postlink: 'https://www.bilibili.com/video/BV1xK4y1K7js',
  },
  {
    id: 'knd3002',
    path: 'knd/3002.png',
    title: '儚さと美しさ',
    subtitle: '宵崎奏 - シークレット・ディスタンス（3星) ',
    prelink: 'https://www.bilibili.com/video/BV1J54y1b7Jp',
    postlink: 'https://www.bilibili.com/video/BV1J54y1b7Jp',
  },
  {
    id: 'mfy2002',
    path: 'mfy/2002.png',
    title: '廃校での出会い',
    subtitle: '朝比奈真冬 - シークレット・ディスタンス（2星) ',
    prelink: 'https://www.bilibili.com/video/BV1nv41177Zf',
    postlink: 'https://www.bilibili.com/video/BV1nv41177Zf',
  },
  {
    id: 'knd2002',
    path: 'knd/2002.png',
    title: 'この春を、あなたと……',
    subtitle: '宵崎奏 - 君と歌う、桜舞う世界で（2星) ',
    prelink: 'https://www.bilibili.com/video/BV1Mp4y187Jw',
    postlink: 'https://www.bilibili.com/video/BV1Mp4y187Jw',
  },
  {
    id: 'knd4003',
    path: 'knd/4003.png',
    title: 'いつか見た夢を',
    subtitle: '宵崎奏 - カラフルフェスティバルガチャ（限定4星) ',
    prelink: 'https://www.bilibili.com/video/BV1T54y1h7Ac',
    postlink: 'https://www.bilibili.com/video/BV1T54y1h7Ac',
  },
  {
    id: 'mfy4003',
    path: 'mfy/4003.png',
    title: '潜る、私の中へ',
    subtitle: '朝比奈真冬 - カラフルフェスティバルガチャ（限定4星) ',
    prelink: 'https://www.bilibili.com/video/BV1564y1Q7Dm',
    postlink: 'https://www.bilibili.com/video/BV1564y1Q7Dm',
  },
  {
    id: 'ena4002',
    path: 'ena/4002.png',
    title: '諦めたくないから',
    subtitle: '东云绘名 - 満たされないペイルカラー（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1FA411u7KM',
    postlink: 'https://www.bilibili.com/video/BV1FA411u7KM?p=2',
  },
  {
    id: 'mfy4002',
    path: 'mfy/4002.png',
    title: '投げかけた言葉',
    subtitle: '朝比奈真冬 - 満たされないペイルカラー（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1zf4y1z7ZQ',
    postlink: 'https://www.bilibili.com/video/BV1zf4y1z7ZQ',
  },
  {
    id: 'knd4002',
    path: 'knd/4002.png',
    title: '想いをメロディーに……',
    subtitle: '宵崎奏 - 満たされないペイルカラー（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1Jo4y1R7Tm',
    postlink: 'https://www.bilibili.com/video/BV1Jo4y1R7Tm',
  },
  {
    id: 'rin3001',
    path: 'rin/3001.png',
    title: '出会いの意味を探して',
    subtitle: '镜音铃 - 満たされないペイルカラー（3星) ',
    prelink: 'https://www.bilibili.com/video/BV1Nh411k7R5?p=3',
    postlink: 'https://www.bilibili.com/video/BV1Nh411k7R5?p=4',
  },
  {
    id: 'mzk2002',
    path: 'mzk/2002.png',
    title: 'トラスト ユー',
    subtitle: '晓山瑞希 - 満たされないペイルカラー（2星) ',
    prelink: 'https://www.bilibili.com/video/BV1Nh411k7R5',
    postlink: 'https://www.bilibili.com/video/BV1Nh411k7R5?p=2',
  },
  {
    id: 'ena4001',
    path: 'ena/4001.png',
    title: '東雲家の年末',
    subtitle: '东云绘名 - セカイのハッピーニューイヤー！（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1Ko4y1o7YD',
    postlink: 'https://www.bilibili.com/video/BV1Ko4y1o7YD',
  },
  {
    id: 'mzk4001',
    path: 'mzk/4001.png',
    title: '屋上のフレンドシップ',
    subtitle: '晓山瑞希 - KAMIKOU FESTIVAL!（4星) ',
    prelink: 'https://www.bilibili.com/video/BV1fv4y1o7cn',
    postlink: 'https://www.bilibili.com/video/BV1fv4y1o7cn?p=2',
  },
  {
    id: 'mfy3002',
    path: 'mfy/3002.png',
    title: '楽しい楽しい二人三脚？',
    subtitle: '朝比奈真冬 - 走れ！体育祭！～実行委員は大忙し～（3星) ',
    prelink: 'https://www.bilibili.com/video/BV1Fa411w7eK?p=3',
    postlink: 'https://www.bilibili.com/video/BV1Fa411w7eK?p=4',
  },
  {
    id: 'mfy4001',
    path: 'mfy/4001.png',
    title: '不自由マスカレード',
    subtitle: '朝比奈真冬 - 囚われのマリオネット（4星）',
    prelink: 'https://www.bilibili.com/video/BV1br4y1w7Eh',
    postlink: 'https://www.bilibili.com/video/BV1oK4y177qr',
  },
  {
    id: 'knd4001',
    path: 'knd/4001.png',
    title: '生きているように',
    subtitle: '宵崎奏 - 囚われのマリオネット（4星）',
    prelink: 'https://www.bilibili.com/video/BV1zK4y177dx',
    postlink: 'https://www.bilibili.com/video/BV17V411y7d9',
  },
  {
    id: 'miku4001',
    path: 'miku/4001.png',
    title: '絶たれた糸',
    subtitle: '初音未来 - 囚われのマリオネット（4星）',
    prelink: 'https://www.bilibili.com/video/BV1ga4y1s75w',
    postlink: 'https://www.bilibili.com/video/BV1354y1r7eG',
  },
  {
    id: 'mzk3002',
    path: 'mzk/3002.png',
    title: '戯れのひととき',
    subtitle: '晓山瑞希 - 囚われのマリオネット（3星）',
    prelink: 'https://www.bilibili.com/video/BV1PT4y1F7u8?p=3',
    postlink: 'https://www.bilibili.com/video/BV1PT4y1F7u8?p=4',
  },
  {
    id: 'ena2002',
    path: 'ena/2002.png',
    title: 'マリオネットドレス',
    subtitle: '东云绘名 - 囚われのマリオネット（2星）',
    prelink: 'https://www.bilibili.com/video/BV1PT4y1F7u8',
    postlink: 'https://www.bilibili.com/video/BV1PT4y1F7u8?p=2',
  },
  {
    id: 'knd3001',
    path: 'knd/3001.png',
    title: '画面の向こうに…',
    subtitle: '宵崎奏 - 3星卡面',
    prelink: 'https://www.bilibili.com/video/BV1MB4y1P7sN',
    postlink: 'https://www.bilibili.com/video/BV1MB4y1P7sN',
  },
  {
    id: 'mfy3001',
    path: 'mfy/3001.png',
    title: '『いい子』の私',
    subtitle: '朝比奈真冬 - 3星卡面',
    prelink: 'https://www.bilibili.com/video/BV1MB4y1P7sN',
    postlink: 'https://www.bilibili.com/video/BV1MB4y1P7sN',
  },
  {
    id: 'ena3001',
    path: 'ena/3001.png',
    title: '最高のアングル',
    subtitle: '东云绘名 - 3星卡面',
    prelink: 'https://www.bilibili.com/video/BV1MB4y1P7sN',
    postlink: 'https://www.bilibili.com/video/BV1MB4y1P7sN',
  },
  {
    id: 'mzk3001',
    path: 'mzk/3001.png',
    title: '譲れないこだわり',
    subtitle: '晓山瑞希 - 3星卡面',
    prelink: 'https://www.bilibili.com/video/BV1MB4y1P7sN',
    postlink: 'https://www.bilibili.com/video/BV1MB4y1P7sN',
  },
  {
    id: 'miku3001',
    path: 'miku/3001.png',
    title: '見守るまなざし',
    subtitle: '初音未来 - 3星卡面',
    prelink: 'https://www.bilibili.com/video/BV1MB4y1P7sN',
    postlink: 'https://www.bilibili.com/video/BV1MB4y1P7sN',
  },
  {
    id: 'knd2001',
    path: 'knd/2001.png',
    title: '25時、ナイトコードで。',
    subtitle: '宵崎奏 - 2星卡面',
    prelink: 'https://www.bilibili.com/video/BV1Sy4y117EZ',
    postlink: 'https://www.bilibili.com/video/BV1Sy4y117EZ',
  },
  {
    id: 'mfy2001',
    path: 'mfy/2001.png',
    title: '25時、ナイトコードで。',
    subtitle: '朝比奈真冬 - 2星卡面',
    prelink: 'https://www.bilibili.com/video/BV1Sy4y117EZ',
    postlink: 'https://www.bilibili.com/video/BV1Sy4y117EZ',
  },
  {
    id: 'ena2001',
    path: 'ena/2001.png',
    title: '25時、ナイトコードで。',
    subtitle: '东云绘名 - 2星卡面',
    prelink: 'https://www.bilibili.com/video/BV1Sy4y117EZ',
    postlink: 'https://www.bilibili.com/video/BV1Sy4y117EZ',
  },
  {
    id: 'mzk2001',
    path: 'mzk/2001.png',
    title: '25時、ナイトコードで。',
    subtitle: '晓山瑞希 - 2星卡面',
    prelink: 'https://www.bilibili.com/video/BV1Sy4y117EZ',
    postlink: 'https://www.bilibili.com/video/BV1Sy4y117EZ',
  },
  {
    id: 'miku2001',
    path: 'miku/2001.png',
    title: '25時、ナイトコードで。',
    subtitle: '初音未来 - 2星卡面',
    prelink: 'https://www.bilibili.com/video/BV1Sy4y117EZ',
    postlink: 'https://www.bilibili.com/video/BV1Sy4y117EZ',
  },
  {
    id: 'knd1001',
    path: 'knd/1001.png',
    title: '音楽に愛された少女',
    subtitle: '宵崎奏 - 1星卡面',
    prelink: 'https://www.bilibili.com/video/BV1pA411H7uZ',
    postlink: 'https://www.bilibili.com/video/BV1pA411H7uZ',
  },
  {
    id: 'mfy1001',
    path: 'mfy/1001.png',
    title: '『いい子』に見られる優等生',
    subtitle: '朝比奈真冬 - 1星卡面',
    prelink: 'https://www.bilibili.com/video/BV1pA411H7uZ',
    postlink: 'https://www.bilibili.com/video/BV1pA411H7uZ',
  },
  {
    id: 'ena1001',
    path: 'ena/1001.png',
    title: 'SNS依存な絵描き',
    subtitle: '东云绘名 - 1星卡面',
    prelink: 'https://www.bilibili.com/video/BV1pA411H7uZ',
    postlink: 'https://www.bilibili.com/video/BV1pA411H7uZ',
  },
  {
    id: 'mzk1001',
    path: 'mzk/1001.png',
    title: '『カワイイ』にこだわる自由人',
    subtitle: '晓山瑞希 - 1星卡面',
    prelink: 'https://www.bilibili.com/video/BV1pA411H7uZ',
    postlink: 'https://www.bilibili.com/video/BV1pA411H7uZ',
  },
];
