export const radioData = [
  {
    id: 'radio010',
    path: '010.png',
    title: '「25时，于夜之电台。」#10 ',
    subtitle: '田边留依 x 铃木实里',
    link: 'https://www.bilibili.com/video/BV1R5411A75n',
  },
  {
    id: 'radio009',
    path: '009.png',
    title: '「25时，于夜之电台。」#9 ',
    subtitle: '田边留依 x 铃木实里',
    link: 'https://www.bilibili.com/video/BV1qp4y1n7Dy',
  },
  {
    id: 'radio008',
    path: '008.png',
    title: '「25时，于夜之电台。」#8 ',
    subtitle: '楠木灯 x 田边留依 x 铃木实里 x 佐藤日向',
    link: 'https://www.bilibili.com/video/BV1GU4y1x7QJ',
  },
  {
    id: 'radio007',
    path: '007.png',
    title: '「25时，于夜之电台。」#7 ',
    subtitle: '铃木实里 × 佐藤日向',
    link: 'https://www.bilibili.com/video/BV17t4y167fb',
  },
  {
    id: 'radio006',
    path: '006.png',
    title: '「25时，于夜之电台。」#6 ',
    subtitle: '佐藤日向 × 楠木灯',
    link: 'https://www.bilibili.com/video/BV18y4y1v78g',
  },
  {
    id: 'radio005',
    path: '005.png',
    title: '「25时，于夜之电台。」#5 ',
    subtitle: '佐藤日向 × 楠木灯',
    link: 'https://www.bilibili.com/video/BV1v5411H7ub',
  },
  {
    id: 'radio004',
    path: '004.png',
    title: '「25时，于夜之电台。」#4 ',
    subtitle: '田边留依 x 铃木实里',
    link: 'https://www.bilibili.com/video/BV1qi4y1c7nQ',
  },
  {
    id: 'radio003',
    path: '003.png',
    title: '「25时，于夜之电台。」#3 ',
    subtitle: '田边留依 x 铃木实里',
    link: 'https://www.bilibili.com/video/BV1DK4y1j7FS',
  },
  {
    id: 'radio002',
    path: '002.png',
    title: '「25时，于夜之电台。」#2 ',
    subtitle: '佐藤日向 x 铃木实里',
    link: 'https://www.bilibili.com/video/BV1ct4y1v7yE',
  },
  {
    id: 'radio001',
    path: '001.png',
    title: '「25时，于夜之电台。」#1 ',
    subtitle: '佐藤日向 x 铃木实里',
    link: 'https://www.bilibili.com/video/BV1pp4y167LJ',
  },
];
